services:
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  
  cytometry-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cytometry-django
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  cytometry-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cytometry-react
    ports:
      - "3000:80" # Map port 3000 on the host to port 80 in the container
    depends_on:
      - cytometry-backend
volumes:
  postgres_data: