# Generated by Django 5.0.6 on 2025-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="time_from_treatment",
        ),
        migrations.AddField(
            model_name="sample",
            name="time_from_treatment_start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
